name: cargo-vet audits

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/aggregate-audits.yml'
      - 'supply-chain/sources.txt'
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  aggregate:
    name: Aggregate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      - run: rustup override set ${{steps.toolchain.outputs.name}}

      - name: Install cargo-vet
        run: cargo install cargo-vet --version ~0.10

      - name: Aggregate audits
        run: cargo vet aggregate --output-file supply-chain/audits.toml supply-chain/sources.txt

      - name: Commit and push aggregated audits
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update aggregated cargo-vet audits
          file_pattern: 'supply-chain/audits.toml'
